### ISSUE TITLE
License Confirmation

### ISSUE THREAD

**Issue by NL33** [NathanaelA/nativescript-localstorage#14]
Hi. On your readme, you say the following:

"This is released under the MIT License, meaning you are free to include this in any type of program -- However for entities that need a support contract, changes, enhancements and/or a commercial license please contact me at http://nativescript.tools."

I was a little confused by the reference to a "commercial license" for an MIT License project. 

Can you confirm that this plugin is free to use for any kind of use, including commercial use, whether by an individual or entity?

**Comment by NathanaelA** [comment]
Well, first of all since I wrote the plugin; I can offer it under as many licenses at the exact same time as I want.  :grinning:     So basically the product is under dual licensing:

So first, the standard MIT license allow you to use it in ANY type of program free of charge which the vast majority of my plugins are licensed under (including this one). 

There are some larger companies that I understand want a supported type commercial license; so I _OPTIONALLY_ offer this license method for those entities and/or for those people who just want to be nice and maybe toss some money my way for all the hard work.     :grinning:

**Comment by NL33** [comment]
That makes sense. Thanks and thanks for the plugin. 

My confusion was about whether you were saying that it was MIT license unless you are a commercial entity, in which case contact you for a commercial license. However, I understand that is not what it means, and as you say the plugin is free to use for any purpose by any type of entity, and if people or entities want extra benefits they can contact you.
Cheers.
