### ISSUE TITLE
Storing data is local storage is safe?

### ISSUE THREAD

**Issue by Omi231** [NathanaelA/nativescript-localstorage#26]
I am using this plugin to store some data in local storage like resource urls, user progress, rewards etc. So, i want to make sure that data is completely safe and user can not access and read/write anything outside the app.

Is this plugin safe for this kind of use?

**Comment by NathanaelA** [comment]
The data is stored in your local app directory.   This means no other apps can get access to the file under **normal** circumstances.

However, someone who has a rooted device (ios or android) can access any file on the file system, which means they can edit it with any program.   

 If you are worried about rooted devices; then that is a much larger conversation on how to secure your app so that they can't edit your files.   Even plugins like nativescript secure storage is not resistant to rooted devices.  Root means I have full access to everything.   So attempting to secure on a rooted device is very hard to do, and one of the reason most apps that are trying for ultra security detect root and refuse to run...
