### ISSUE TITLE
Nativescript-vue: no errors shown, but data not saved

### ISSUE THREAD

**Issue by BlackXDragon** [NathanaelA/nativescript-localstorage#29]
I used this library with my nativescript-vue project but my data isn't getting saved. I'm not getting any compile or runtime errors. Please help.

Code: https://github.com/BlackXDragon/NativeScript-vue-localstorage-test

**Comment by BlackXDragon** [comment]
@NathanaelA, please help

**Comment by NathanaelA** [comment]
@BlackXDragon - Actually your issue is your code has a bug:
https://nativescript-vue.org/en/docs/elements/components/text-field/
For the `Text` component you need to use `v-model` not `:text` for **two** way binding.    If you `console.log` out the this.msg you will see it is still blank, so you are passing in blank to the localstorage and of course you will then get blank back.
